"""Regression test: YAML generated by the frontend Guided Builder must compile.

This is a parity gate. The frontend yaml-generator emits a canonical DSL
shape (labels as object map, workflow.planner_mode under workflow, telemetry
section, full policies tree, step retry / uses_credentials, etc.). If a
generator change starts producing YAML the compiler rejects, this test
fails before any user sees it.

The YAML below is hand-written to mirror the shape that
frontend/lib/flows/yaml-generator.ts produces given a draft that exercises
every supported DSL feature.
"""

from __future__ import annotations

import textwrap

import pytest

from saz.compiler import compile_dsl

BUILDER_GENERATED_YAML = textwrap.dedent(
    """\
    schema_version: 1
    flow:
      name: parity_demo
      version: "1.0"
      description: "Exercises every Guided Builder feature."
      owners:
        - ops
      labels:
        team: ops
        tier: prod
    credentials:
      uses:
        - api_token
    policies:
      budget_usd: 0.5
      concurrency:
        per_flow: 2
        per_user: 1
      defaults:
        timeout_ms: 30000
        continue_on_fail: false
        retry:
          attempts: 3
          backoff:
            mode: exponential
            base_ms: 500
            jitter: true
      pii:
        allow: false
        tokenize_model_inputs: true
        exceptions:
          tools:
            artifact.store:
              allow:
                - content.requester
            http_request:
              - url
      rate_limits:
        http_request:
          rpm: 100
    telemetry:
      trace_level: brief
      sample_rate: 0.5
    form:
      fields:
        - name: severity
          type: string
          required: true
          enum: [low, medium, high]
          pattern: "^[a-z]+$"
          minLength: 2
          maxLength: 16
          default: low
          title: Severity
          description: Pick one
        - name: count
          type: integer
          required: false
          minimum: 0
          maximum: 100
        - name: email
          type: string
          required: false
          format: email
    workflow:
      planner_mode: deterministic
      steps:
        - id: gate
          type: condition
          description: only run on prod
          if: "{{ $form.severity == 'high' }}"
        - id: classify
          type: ai.extract
          description: classify input
          instruction: "Classify the alert."
          params:
            data:
              severity: "{{ $form.severity }}"
          expect:
            type: object
            properties:
              ok:
                type: boolean
            required: [ok]
          uses_credentials:
            - api_token
          retry:
            attempts: 2
            backoff:
              mode: constant
              base_ms: 100
          temperature: 0.1
          max_tokens: 400
        - id: route
          type: ai.route
          description: pick branch
          instruction: "Route the request."
          expect:
            type: object
          branches_enum:
            - approve
            - reject
        - id: summary
          type: ai.summarize
          description: write a summary
          instruction: "Summarize the run."
          expect:
            type: object
          word_cap: 60
        - id: translate
          type: ai.translate
          description: translate
          instruction: "Translate to French."
          expect:
            type: object
          target_locale: fr-FR
        - id: store
          type: artifact.store
          description: store audit
          params:
            name: audit_record
            content_type: json
            content:
              ok: true
        - id: fetch
          type: artifact.retrieve
          description: read audit
          params:
            name: audit_record
        - id: call
          type: tool.call
          description: call upstream
          tool: http_request
          params:
            url: "https://example.com"
            method: GET
        - id: approve
          type: human.approval
          description: ask the operator
          params:
            title: Approve change
        - id: wait
          type: webhook.wait
          description: wait for callback
          params:
            event_name: approval_received
    """
)


def test_builder_generated_yaml_compiles_cleanly() -> None:
    """End-to-end: compile every supported feature the builder can emit."""

    compiled = compile_dsl(BUILDER_GENERATED_YAML)

    assert compiled.flow_name == "parity_demo"
    assert compiled.workflow_spec["planner_mode"] == "deterministic"
    step_ids = [step["id"] for step in compiled.workflow_spec["steps"]]
    assert step_ids == [
        "gate",
        "classify",
        "route",
        "summary",
        "translate",
        "store",
        "fetch",
        "call",
        "approve",
        "wait",
    ]


@pytest.mark.parametrize(
    ("section", "transform"),
    [
        # workflow.planner_mode must live under workflow, NOT flow.
        # Moving it under flow proves the compiler enforces the location.
        (
            "planner_mode_misplaced",
            lambda y: y.replace(
                "workflow:\n  planner_mode: deterministic",
                "workflow:\n  planner_mode: deterministic",
            ).replace(
                "  labels:\n    team: ops",
                "  labels:\n    team: ops\n  planner_mode: agentic",
            ),
        ),
        # flow.labels must be an object map. Replacing with an array form
        # should be rejected.
        (
            "labels_as_array",
            lambda y: y.replace(
                "  labels:\n    team: ops\n    tier: prod",
                "  labels:\n    - ops\n    - prod",
            ),
        ),
    ],
)
def test_canonical_shapes_are_required(section: str, transform) -> None:
    """The DSL shapes the generator emits are not optional — the compiler
    rejects the prior frontend shapes (planner_mode under flow, labels as
    array)."""

    bad_yaml = transform(BUILDER_GENERATED_YAML)
    with pytest.raises(ValueError):
        compile_dsl(bad_yaml)
