import type { FlowDraft, WorkflowStepDraft } from './types';

/**
 * Generate unified DSL YAML from FlowDraft
 */
export function draftToUnifiedYaml(draft: FlowDraft): string {
  const lines: string[] = [];

  // Header comment
  lines.push(`# Generated by Saz Flow Builder`);
  lines.push(`# Flow: ${draft.name}`);
  lines.push(`schema_version: ${draft.schema_version || 1}`);
  lines.push('');

  // Flow metadata
  lines.push('flow:');
  lines.push(`  name: ${draft.name}`);
  lines.push(`  version: "${draft.version}"`);
  if (draft.description) {
    lines.push(`  description: ${quoteIfNeeded(draft.description)}`);
  }
  if (draft.planner_mode) {
    lines.push(`  planner_mode: ${draft.planner_mode}`);
  }
  if (draft.owners && draft.owners.length > 0) {
    lines.push(`  owners:`);
    draft.owners.forEach((owner) => lines.push(`    - ${owner}`));
  }
  if (draft.labels && draft.labels.length > 0) {
    lines.push(`  labels:`);
    draft.labels.forEach((label) => lines.push(`    - ${label}`));
  }
  lines.push('');

  // Form
  if (draft.form_fields && draft.form_fields.length > 0) {
    lines.push('form:');
    lines.push('  fields:');
    draft.form_fields.forEach((field) => {
      lines.push(`    - name: ${field.name}`);
      lines.push(`      type: ${field.type}`);
      lines.push(`      required: ${field.required}`);
      if (field.description) {
        lines.push(`      description: ${quoteIfNeeded(field.description)}`);
      }
      if (field.help_text) {
        lines.push(`      help_text: ${quoteIfNeeded(field.help_text)}`);
      }
      if (field.format) {
        lines.push(`      format: ${field.format}`);
      }
      if (field.default !== undefined) {
        lines.push(`      default: ${JSON.stringify(field.default)}`);
      }
    });
    lines.push('');
  }

  // Triggers
  lines.push('triggers:');
  lines.push(`  manual: ${draft.triggers.manual}`);
  if (draft.triggers.webhook?.enabled) {
    lines.push('  webhook:');
    if (draft.triggers.webhook.path) {
      lines.push(`    path: "${draft.triggers.webhook.path}"`);
    }
    if (draft.triggers.webhook.event) {
      lines.push(`    event: "${draft.triggers.webhook.event}"`);
    }
  }
  if (draft.triggers.schedule?.enabled) {
    lines.push('  schedule:');
    if (draft.triggers.schedule.cron) {
      lines.push(`    cron: "${draft.triggers.schedule.cron}"`);
    }
    if (draft.triggers.schedule.timezone) {
      lines.push(`    timezone: "${draft.triggers.schedule.timezone}"`);
    }
  }
  lines.push('');

  // Workflow steps
  if (draft.workflow_steps && draft.workflow_steps.length > 0) {
    lines.push('workflow:');
    lines.push('  steps:');
    draft.workflow_steps.forEach((step, idx) => {
      if (idx > 0) lines.push('');
      lines.push(`    - id: ${step.id}`);
      lines.push(`      type: ${step.type}`);
      if (step.name) {
        lines.push(`      name: ${quoteIfNeeded(step.name)}`);
      }
      if (step.description) {
        lines.push(`      description: ${quoteIfNeeded(step.description)}`);
      }
      if (step.instruction) {
        if (step.instruction.includes('\n')) {
          lines.push(`      instruction: |`);
          step.instruction.split('\n').forEach((line) => {
            lines.push(`        ${line}`);
          });
        } else {
          lines.push(`      instruction: ${quoteIfNeeded(step.instruction)}`);
        }
      }

      // Step-specific fields
      if (step.params && Object.keys(step.params).length > 0) {
        lines.push(`      params:`);
        lines.push(...yamlifyObject(step.params, 8));
      }
      if (step.schema) {
        lines.push(`      schema:`);
        lines.push(...yamlifyObject(step.schema, 8));
      }
      if (step.expect) {
        lines.push(`      expect:`);
        lines.push(...yamlifyObject(step.expect, 8));
      }
      if (step.branches_enum && step.branches_enum.length > 0) {
        lines.push(`      branches_enum:`);
        step.branches_enum.forEach((branch) => lines.push(`        - ${branch}`));
      }
      if (step.tool) {
        lines.push(`      tool: ${step.tool}`);
      }
      if (step.temperature !== undefined) {
        lines.push(`      temperature: ${step.temperature}`);
      }
      if (step.max_tokens !== undefined) {
        lines.push(`      max_tokens: ${step.max_tokens}`);
      }
      if (step.word_cap !== undefined) {
        lines.push(`      word_cap: ${step.word_cap}`);
      }
    });
    lines.push('');
  }

  // Policies
  lines.push('policies:');
  if (draft.policies.budget_usd !== undefined) {
    lines.push(`  budget_usd: ${draft.policies.budget_usd}`);
  }
  if (draft.policies.pii_policy) {
    lines.push(`  pii:`);
    const allow = draft.policies.pii_policy === 'allow_with_warning';
    lines.push(`    allow: ${allow}`);
    if (draft.policies.pii_policy === 'tokenize') {
      lines.push(`    tokenize_model_inputs: true`);
    }
  }
  if (
    draft.policies.timeout_ms ||
    draft.policies.continue_on_fail !== undefined ||
    draft.policies.rate_limits
  ) {
    lines.push('  defaults:');
    if (draft.policies.timeout_ms) {
      lines.push(`    timeout_ms: ${draft.policies.timeout_ms}`);
    }
    if (draft.policies.continue_on_fail !== undefined) {
      lines.push(`    continue_on_fail: ${draft.policies.continue_on_fail}`);
    }
  }
  if (draft.policies.rate_limits?.http_request?.rpm) {
    lines.push('  rate_limits:');
    lines.push('    http_request:');
    lines.push(`      rpm: ${draft.policies.rate_limits.http_request.rpm}`);
  }
  lines.push('');

  // Credentials
  if (draft.credentials && draft.credentials.length > 0) {
    lines.push('credentials:');
    lines.push('  uses:');
    draft.credentials.forEach((cred) => lines.push(`    - ${cred}`));
  }

  return lines.join('\n');
}

function quoteIfNeeded(str: string): string {
  // If string contains special chars, newlines, or starts with special chars, quote it
  if (/[:{}[\],&*#?|\-<>=!%@`]/.test(str) || str.includes('\n') || /^[\s]/.test(str)) {
    return `"${str.replace(/"/g, '\\"')}"`;
  }
  return str;
}

function yamlifyObject(obj: any, indent: number): string[] {
  const lines: string[] = [];
  const spaces = ' '.repeat(indent);

  if (Array.isArray(obj)) {
    obj.forEach((item) => {
      if (typeof item === 'object') {
        lines.push(`${spaces}- `);
        lines.push(...yamlifyObject(item, indent + 2).map((l) => `  ${l}`));
      } else {
        lines.push(`${spaces}- ${JSON.stringify(item)}`);
      }
    });
  } else if (typeof obj === 'object' && obj !== null) {
    Object.entries(obj).forEach(([key, value]) => {
      if (typeof value === 'object' && value !== null) {
        lines.push(`${spaces}${key}:`);
        lines.push(...yamlifyObject(value, indent + 2));
      } else {
        lines.push(`${spaces}${key}: ${JSON.stringify(value)}`);
      }
    });
  }

  return lines;
}
